### ISSUE TITLE
deny-back: allow flag does not allow members to use back, can we get a second flag that alows members but blocks others?

### ISSUE THREAD

**Issue by TomLewis** [No-Not-Jaden/denyback#2]
Can we please get 2 flags.
`deny-back: allow` = block everyone using /back
`deny-backnonmember: allow` = block all non members from using `/back` but not the members of that WG region.

The issue im having is im using areashop https://github.com/md5sha256/AreaShop
Ive added the `deny-back: allow` to the default.yml which blocks shop owners from using back! I intended to allow shop owners to use back and prevent others using back into their shops, but thats not how this flags works I found out!

I also tried  `deny-nonmembers: true` in the config, but this seems like its a global region changer, for all WG regions on the server? 
Which fixes the shops BUT then all other regions on the server now have back blocked for everyone! haha

so its a catch 22.

I suggest a new flag so then we can just add that one to regions where we want nonmember access but block everyone else.

**Comment by No-Not-Jaden** [comment]
DenyBack can already block only nonmembers with the nonmembers group trait. To use this with AreaShop, use `deny-back: 'allow g:non_members'`. To set this manually in a region, do the command `/rg flag (region name) deny-back -g nonmembers allow`
