### ISSUE TITLE
If a world is removed or renamed throws errors!

### ISSUE THREAD

**Issue by TomLewis** [No-Not-Jaden/denyback#3]
Copied/pasted my configs to a test server with differnt worlds for testing areashop as I use deny back for shops with areashop and got a lot a couple of errors;
https://gist.github.com/TomLewis/ce7a93d3e2c8e7ee41e9082a7e1a71ed

I presume its loading the locations.yml into memory, and as the world does not exist on my test server its throwing these exceptions.

**Comment by No-Not-Jaden** [comment]
Thanks for reporting this. You are probably correct in why the error is occurring. I've changed the code and will test it later today when I'm at my PC. An update will come out by the end of the day.

**Comment by No-Not-Jaden** [comment]
I've updated the plugin on [Spigot](https://www.spigotmc.org/resources/deny-back-commands-into-worldguard-regions-and-griefprevention-claims.90759/update?update=541887). I'm now using a different method (but similar) to save locations. You may still get the errors once after updating, but it should be fixed after the plugin saves to the files once.

**Comment by TomLewis** [comment]
Will it convert from the previous file?

**Comment by No-Not-Jaden** [comment]
Yes it will. Any locations that were saved in worlds that don't exist will be ignored.
