### ISSUE TITLE
High resource use

### ISSUE THREAD

**Issue by TomLewis** [No-Not-Jaden/denyback#4]
Doing a timings today with only 6 players online, very quiet, DenyBack is very heavy use in timings, is there a way you can optimize 

![image](https://github.com/No-Not-Jaden/denyback/assets/144046/0d592470-56d1-4ce6-9549-c3c7f24c88dd)

**Comment by No-Not-Jaden** [comment]
That report is a bit misleading. The task that is causing lag is DenyBack's autosave which is on an interval of 36000 ticks = 30 minutes. It takes about 2.2 seconds to save the player's locations. Thinking about it now, autosaving at a high interval won't provide a lot of accuracy if the server crashes, so I'm adding an option to change the interval or disable it entirely. I also changed it to run async which may help with performance. I'll be posting this update shortly on spigot.

**Comment by TomLewis** [comment]
ahhh super job!
